Added connection timeout
neo4j/neo4j-dotnet-driver pull request #134
Opened 2016-12-23 14:21 UTC by zhenlineo

Default to 5s
Abstracted ConnectionSettings class to include all related settings for a connection inside and pass through to SocketConnection

2016-12-27 16:04 UTC, lutovich requested changes
@zhenlineo review round completed

2016-12-27 16:04 UTC, lutovich commented on Neo4j.Driver/Neo4j.Driver/Internal/ConnectionSettings.cs
> +            Throw.ArgumentNullException.IfNull(initialServerUri, nameof(initialServerUri));
Could `Contract.Requires` be used here? As described here https://msdn.microsoft.com/en-us/library/dd264808(v=vs.110).aspx

2016-12-27 16:04 UTC, lutovich commented on Neo4j.Driver/Neo4j.Driver/Internal/Connector/SocketConnection.cs
> +                var connected = Task.Run(() => _client.Start()).Wait(_connectionTimeout);
Shouldn't we cancel the `_client.Start()` task if `!connected`?
Could it still remain running in the background?
I do not know for sure, reading these articles:
https://msdn.microsoft.com/en-us/library/mt674886.aspx
https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/dd235606(v=vs.110).aspx

Would be nice to have this tested as well.

2017-01-04 14:48 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/Internal/ConnectionSettings.cs
> +            Throw.ArgumentNullException.IfNull(initialServerUri, nameof(initialServerUri));
I did not find this lib in .net core libs

2017-01-04 15:48 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/Internal/Connector/SocketConnection.cs
> +                var connected = Task.Run(() => _client.Start()).Wait(_connectionTimeout);
We will close the whole connection (where we call `_client.Dispose()`) in `ConnectionPool.Acquire` if failed to create a new connection.

2017-01-05 09:43 UTC, lutovich approved these changes

2017-01-05 09:43 UTC, merged