refactor of packstream & bolt layer
neo4j/neo4j-dotnet-driver pull request #205
Opened 2017-07-29 19:26 UTC by ali-ince

Refactored packstream & bolt layer to better handle async logic

2017-07-31 12:25 UTC, zhenlineo requested changes
Have not finished the whole PR, but here are some key notes that we need to clarify before we continue.

2017-07-31 12:25 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/Internal/Connector/SocketClient.cs
> +            return _writer.FlushAsync();
This changes the original flow. The `catch` cause was aiming to catch any error to flush.

2017-07-31 12:25 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/Internal/IO/BoltReader.cs
> +                    {
Maybe we could abstract the handling of the structure into a separate method that both async and sync method could call?

2017-07-31 12:25 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/Internal/IO/BoltReader.cs
> +            _chunkReader.ReadNextChunk(_bufferStream);
If I got the code here correctly, the whole logic depends on the assumption that a whole message (such as a Record message) could be put into `_bufferStream`. I do not think that we could assume on that.

Pls correct me if I understand this part wrongly.

2017-07-31 12:25 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/Internal/IO/ChunkReader.cs
> +                        break;
So this while loop will not stop until we've reached a `0x00 00`, does this mean that we will not stop putting more data into `targetStream` (a.k.a. `boltReader._bufferStream`) until we pulled the whole message into `targetStream`?

As I committed in `boltReader` I do not think we could assume that we could always pull the whole message into memory. CC @technige I need some inputs from you too.

Similar for writer, when a chunk is finished, then we should flush it immediately.

2017-07-31 14:08 UTC, ali-ince commented on Neo4j.Driver/Neo4j.Driver/Internal/Connector/SocketClient.cs
> +            return _writer.FlushAsync();
Fixed it

2017-07-31 14:51 UTC, ali-ince commented on Neo4j.Driver/Neo4j.Driver/Internal/IO/BoltReader.cs
> +                    {
Done :)

2017-08-01 08:56 UTC, zhenlineo approved these changes

2017-08-01 14:49 UTC, merged