Avoiding throw AggregateException
neo4j/neo4j-dotnet-driver pull request #217
Opened 2017-08-10 15:33 UTC by zhenlineo

2017-08-14 09:25 UTC, ali-ince requested changes

2017-08-14 09:25 UTC, ali-ince commented on Neo4j.Driver/Neo4j.Driver.Tests/RetryLogicTests.cs
> +            var error = e.InnerException as AggregateException;
We shall also check for e's type against ServiceUnavailableException.

2017-08-14 09:25 UTC, ali-ince commented on Neo4j.Driver/Neo4j.Driver.IntegrationTests/DirectDriver/TransactionIT.cs
> +                var error = e.InnerException as AggregateException;
We shall also check for e's type against ServiceUnavailableException.

2017-08-16 08:47 UTC, zhenlineo commented
@ali-ince Done

2017-08-16 09:17 UTC, merged