Spelling
neo4j/neo4j-dotnet-driver pull request #275
Opened 2018-03-02 15:40 UTC by jsoref

Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

2018-03-02 15:48 UTC, zhenlineo commented
Hello,

Thanks very much for contributing. Would you mind to sign our CLA https://neo4j.com/developer/cla/ to be able to contribute us?

Also could you smash all commits into one commit?

Thanks again.
Zhen

2018-03-02 16:18 UTC, jsoref commented
If you're ok w/ the commits, I'm happy to squash (probably Sunday).

I prefer to leave things as individual commits in case someone objects to a given correction / to enable rebasing.

2018-03-02 16:31 UTC, zhenlineo requested changes

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK/DriverResultApi.feature
> +  Scenario: Access Statement parameterised
Please ignore any spelling errors in path `Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK`
They are auto generated.

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK/DriverResultApi.feature.cs
> +        [Xunit.TraitAttribute("Description", "Access Statement parameterised")]
Same for this file in path `Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK`

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK/DriverResultApiSteps.cs
> +                throw new InvalidOperationException($"Cannot understand the type {expected} in the feature file, while the actual type returned from the server is {actual}");
Same for this file in path `Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK`

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK/DriverStatementResultNavigation.feature
> +  Scenario: Record should contain key and value and value should be retrievable by index
Same for this file in path Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK/DriverStatementResultNavigation.feature.cs
> +        [Xunit.TraitAttribute("Description", "Record should contain key and value and value should be retrievable by index")]
Same for this file in path Neo4j.Driver/Neo4j.Driver.Tck.Tests/TCK

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/V1/Config.cs
> +        /// Gets or sets how to determine the authenticity of an encryption certificate provided by the Neo4j instance we are connectiong to.
This was not an error.

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/V1/GraphDatabase.cs
> +        ///     The protocol <c>bolt</c> should be used when creating a driver connectiong to the Neo4j instance directly.
Same for this file `connecting` was correct.

2018-03-02 16:31 UTC, zhenlineo commented on Neo4j.Driver/Neo4j.Driver/V1/IAuthToken.cs
> +    ///     The scheme used must be also supported by the Neo4j instance you are connectiong to.
Same for this file. The `connecting` was correct.

2018-03-04 02:37 UTC, jsoref commented
@zhenlineo: updated. Let me know if you're ok w/ this, and I'll squash...

2018-03-12 09:02 UTC, zhenlineo commented
@jsoref Hi, could you squash the commits then we shall merge your PR?

2018-03-14 23:48 UTC, jsoref commented
@zhenlineo: squashed

2018-03-15 09:09 UTC, zhenlineo approved these changes

2018-03-15 09:11 UTC, merged